<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-U4BDLB7" failures="1" tests="1" name="Default test" time="233.968" errors="0" timestamp="2023-06-04T16:36:36 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="219.258">
    <failure type="java.lang.AssertionError" message="expected [Cancelled] but found [Create]">
      <![CDATA[java.lang.AssertionError: expected [Cancelled] but found [Create]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepdefinitions.Request_for_financing_steps.check_the_status_its_on_cancel(Request_for_financing_steps.java:537)
at âœ½.Check the Status its on cancel(file:///C:/Users/priya/git/AZENTIO-FMS_3/Azentio_FMS_Gowtham/src/test/java/features/Request_for_Financing.feature:82)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
