<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-U4BDLB7" failures="1" tests="1" name="Runner.TestApplication" time="219.258" errors="0" timestamp="2023-06-04T16:36:37 IST" skipped="0">
  <testcase classname="Runner.TestApplication" name="runScenario" time="219.258">
    <failure message="expected [Cancelled] but found [Create]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Cancelled] but found [Create]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepdefinitions.Request_for_financing_steps.check_the_status_its_on_cancel(Request_for_financing_steps.java:537)
at âœ½.Check the Status its on cancel(file:///C:/Users/priya/git/AZENTIO-FMS_3/Azentio_FMS_Gowtham/src/test/java/features/Request_for_Financing.feature:82)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Runner.TestApplication -->
